# Generated by Django 4.2.6 on 2023-10-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default='10:40'),
            preserve_default=False,
        ),
    ]
