# Generated by Django 5.0a1 on 2023-10-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=250)),
                ('dp', models.ImageField(upload_to='pics')),
                ('about', models.TextField()),
            ],
        ),
    ]
