# Generated by Django 5.0a1 on 2023-10-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
