# Generated by Django 5.0rc1 on 2023-11-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='img',
            field=models.ImageField(default='fffg', upload_to='pics'),
            preserve_default=False,
        ),
    ]
