# Generated by Django 5.0rc1 on 2023-12-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_department_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='link',
            field=models.URLField(default='efdgg'),
            preserve_default=False,
        ),
    ]
