# Generated by Django 5.0rc1 on 2023-12-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_department_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
