# Generated by Django 5.0a1 on 2023-10-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sddhasddshadsa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
