# Generated by Django 5.0a1 on 2023-10-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dirc_name',
            field=models.TextField(default='dhdfhd'),
            preserve_default=False,
        ),
    ]
